name: Docker

on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: actions-hub/docker/login@master
          env:
              DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build :latest
          if: success()
          run: docker build -t blester125/${{ github.repository }}:latest .
        - name: Push to Docker Hub
          if: success()
          uses: actions-hub/docker@master
          with:
              args: push blester125/${{ github.repository }}:latest .
